language: python
sudo: false
matrix:
  include:
  - python: 2.7
  - python: 3.2
  - python: 3.3
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - python: 3.8
  - python: 3.9
  - python: nightly
  - python: pypy3
  allow_failures:
  - python: 3.2  # EOL
  - python: 3.3  # EOL
  - python: 3.4  # EOL
  - python: nightly
before_install:
- if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'coverage<4.0.0'; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install 'pyflakes<2.0.0'; fi
- pip install codecov
install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
- pip install -e .
script:
- python setup.py test
after_success:
- codecov
