language: python
sudo: false
matrix:
  include:
  - python: 2.7
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - python: 3.8
  - python: 3.9
  - python: nightly
  - python: pypy3
  allow_failures:
  - python: nightly
before_install:
- pip install codecov
install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
- pip install -e .
script:
- python setup.py test
after_success:
- codecov
