language: python
sudo: false
matrix:
  include:
  - python: 2.7
  - python: 3.2
  - python: 3.3
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - python: 3.8
  - python: 3.9
  - python: nightly
  - python: pypy3
  allow_failures:
  - python: 3.2  # EOL
  - python: 3.3  # EOL
  - python: 3.4  # EOL
  - python: nightly
before_install:
- if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'coverage<4.0.0'; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install 'pyflakes<2.0.0'; fi
- pip install codecov
install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
- pip install -e .
script:
- python setup.py test
after_success:
- codecov
deploy:
  provider: pypi
  user: p1c2u
  password:
    secure: mQCKjaqTpkDhTRCSZtdt5d3tOs/d1vc8PDAna5Gr5prMbosq5stG3HdTK3qK5AbfNghclFYZH726zD2i4LdBWmHoA50TJn6mud3k0Byt+fEpnFIHgb8B2hhOQiiG/LxO1X+oRQI+2NL6TQagxJZzSArqaY4p83RAoLNjlf8LpgQu6qjERFkxMaSCrDfDWJ8MBFINMiZ5ZCq3NF8Rclaesv7HKAaYc8591grjouR8FBoVIPG7EWCZP8lp4CVEz6XlBZV8DDmUuhIhqWRkf6jS1zMbd0fUB7iKh2vHDHSWx9kGsxSRCqISDy3ywVUcee6O5M06RwzlpDSML+vuBHYvr8KX5LWSoaOcZfRNjGYIv437t+81Bl1d34GogI/Abm8WxG92KYt5+//6bKk7byck76ZLvuxV/lPtLjg0Caya9zVk/SE0GEa5N+Da04SHJqML88dS9ImbKchOnP1nUb/oUFA8SADFaMonxLbqe2k+PTLymZVTv0apPpiDXKpUF0K1+1WdggDRyr9WFhoBB7KYme6uQLLi78vmDo4gZzG+NvPYoux/VVsbm+upZdqRFL1jX8GGYMu/VbFwN3EHCAH3b6kFZFijZuTgCsIGvMfU2j/tJpLGUJLN8uLJlN88PqPxU4iz7lVKRU29hLwnCWY9yjPdTCZn0gdcZuosv6leNlc=
  distributions: sdist bdist_wheel
  on:
    tags: true
